from __future__ import annotations

import json
import re
import unittest
from pathlib import Path

from radar.constants import CLIENT_SECTIONS
from radar.filters import SECTION_EVENT_TYPES
from radar.sections import SECTION_SOURCE_SUMMARIES

ROOT = Path(__file__).resolve().parents[2]


class QmlContractTests(unittest.TestCase):
    def test_manifest_pairs_panel_with_optional_collapsible_bar_widget(self) -> None:
        manifest = json.loads((ROOT / "manifest.json").read_text(encoding="utf-8"))
        self.assertEqual(["panel", "bar-widget"], manifest["kinds"])
        self.assertNotIn("keepLoaded", manifest)
        self.assertTrue((ROOT / manifest["entryPoints"]["panel"]).is_file())
        self.assertTrue((ROOT / manifest["entryPoints"]["barWidget"]).is_file())
        self.assertEqual("right", manifest["barWidget"]["defaultSection"])
        self.assertEqual("assets/io.github.mtolhuys.news-radar.svg", manifest["icon"])
        self.assertTrue((ROOT / manifest["icon"]).is_file())
        icon = (ROOT / manifest["icon"]).read_text(encoding="utf-8")
        self.assertIn("#9ece6a", icon)
        self.assertIn("#ffad24", icon)
        self.assertIn('translate(64 64) scale(.075) translate(-600 -600)', icon)
        self.assertIn('circle cx="64" cy="64" r="19"', icon)
        self.assertTrue((ROOT / "assets/readme-banner.svg").is_file())
        marketplace_preview = (ROOT / "preview.png").read_bytes()
        self.assertEqual(b"\x89PNG\r\n\x1a\n", marketplace_preview[:8])
        self.assertEqual(
            (1200, 675),
            (
                int.from_bytes(marketplace_preview[16:20], "big"),
                int.from_bytes(marketplace_preview[20:24], "big"),
            ),
        )
        walkthrough = (ROOT / "preview.gif").read_bytes()
        self.assertIn(walkthrough[:6], (b"GIF87a", b"GIF89a"))
        self.assertEqual((960, 573), (
            int.from_bytes(walkthrough[6:8], "little"),
            int.from_bytes(walkthrough[8:10], "little"),
        ))
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
        self.assertIn("(assets/readme-banner.svg)", readme)
        self.assertIn("(preview.gif)", readme)
        self.assertEqual(
            {"appId": "org.quickshell", "title": "📰 Omarchy News Radar"},
            manifest["windowIdentity"],
        )

        widget = (ROOT / "src/BarWidget.qml").read_text(encoding="utf-8")
        self.assertIn("visible: barVisible", widget)
        self.assertIn("implicitWidth: button.implicitWidth", widget)
        self.assertIn('"--bar-visible", "false"', widget)
        self.assertIn("Qt.RightButton", widget)
        self.assertIn("refresh-if-due", widget)
        self.assertIn('path: root.cacheBase + "/omarchy-news-radar/feed.json"', widget)
        self.assertIn("readonly property int refreshMinimumAgeSeconds: 5 * 60", widget)
        self.assertIn("function scheduleRefresh(result)", widget)
        self.assertIn("readonly property int initialRefreshDelayMs: 1800", widget)
        self.assertIn("readonly property int refreshFloorSeconds: 5", widget)
        self.assertIn("if (!refreshProc.running)", widget)
        self.assertNotIn("refreshTimer.interval = 1800", widget)
        self.assertIn("nextCheckInSeconds", widget)
        self.assertIn('String(widgetMetadata.sourceDir) + "/bin/news-radar-shortcut"', widget)
        self.assertIn('shortcutMigrationProc.command = [shortcutHelperPath, "migrate-owned-legacy"]', widget)
        self.assertIn("property bool componentReady: false", widget)
        self.assertIn("property bool shortcutMigrationAttempted: false", widget)
        self.assertIn("property bool indicatorUpdatePending: false", widget)
        self.assertIn('runHelper(installedProc, ["installed"])', widget)
        self.assertIn('"indicator", "--installed-json", JSON.stringify(pluginIds)', widget)
        self.assertIn("onExited: function() { root.startIndicatorUpdate() }", widget)
        self.assertNotIn("installedPluginsReady", widget)

    def test_panel_uses_plain_text_and_structural_process_arguments(self) -> None:
        qml = (ROOT / "src/Panel.qml").read_text(encoding="utf-8")
        self.assertIn("function open(payloadJson)", qml)
        self.assertIn("function close()", qml)
        self.assertIn("function runtimeIdentity()", qml)
        self.assertIn("command = [helperPath].concat(argumentsList)", qml)
        self.assertIn("textFormat: Text.PlainText", qml)
        self.assertIn("textFormat: root.inspectorArticleMode ? Text.RichText : Text.PlainText", qml)
        self.assertIn("linkColor: Color.accent", qml)
        self.assertIn("articleBodyHtml(inspectorBodySegments(), Color.accent)", qml)
        self.assertIn("onLinkActivated", qml)
        self.assertIn("function openArticleLink(url)", qml)
        self.assertIn("function inspectorBodyText()", qml)
        self.assertIn("RadarModel.articleBodyHtml", qml)
        self.assertIn("pluginUpdateNotice", qml)
        self.assertIn("Layout.preferredWidth: 0", qml)
        self.assertIn("id: sectionTitleText", qml)
        self.assertIn("Update plugin", qml)
        self.assertIn('"update-status"', qml)
        self.assertIn('"update-apply"', qml)
        self.assertIn("RadarModel.acceptedHttpsUrl", qml)
        self.assertNotIn("Qt.openUrlExternally", qml)
        self.assertNotIn("shell -c", qml)
        self.assertIn("TUNE YOUR RADAR", qml)
        self.assertIn("Story images", qml)
        self.assertIn("Top-bar newspaper", qml)
        self.assertIn("function tuneNewspaperGeometry()", qml)
        self.assertIn("property bool localStateReady: false", qml)
        self.assertIn("if (!localStateReady || stateMutationPending || preferencesProc.running) return", qml)
        self.assertIn('startProcess(preferencesProc, ["read"])', qml)
        self.assertIn("enabled: root.localStateReady && !root.stateMutationPending && !preferencesProc.running", qml)
        self.assertIn("No stories in this edition include a validated image.", qml)
        self.assertIn('visible: !root.cachedFeed && !root.refreshing && text !== ""', qml)
        self.assertNotIn('text: root.feedStatus + " · " + root.sourceHealth', qml)
        self.assertNotIn("Pages cache ≤10m", qml)
        self.assertNotIn("KEYBOARD  Tab/Shift+Tab sections", qml)
        self.assertIn('placeholderText: "Search news  /"', qml)
        self.assertIn("function sectionSummaryText()", qml)
        self.assertIn("readonly property bool popupBgIsLight", qml)
        # Panel chrome is title-only; Apps/desktop keep the application icon assets.
        self.assertIn("No in-panel mark", qml)
        self.assertNotIn("../assets/io.github.mtolhuys.news-radar-panel.svg", qml)
        self.assertNotIn("../assets/io.github.mtolhuys.news-radar-panel-light.svg", qml)
        self.assertFalse((ROOT / "assets/io.github.mtolhuys.news-radar-light.svg").exists())
        for panel_mark_name in (
            "io.github.mtolhuys.news-radar-panel.svg",
            "io.github.mtolhuys.news-radar-panel-light.svg",
        ):
            panel_mark = (ROOT / "assets" / panel_mark_name).read_text(encoding="utf-8")
            self.assertNotIn("#111418", panel_mark)
            self.assertNotIn("<rect", panel_mark)
            self.assertIn('circle cx="64" cy="64" r="19"', panel_mark)
        self.assertIn("color: Color.popups.border", qml)
        self.assertIn("FloatingWindow", qml)
        self.assertNotIn("PanelWindow", qml)
        self.assertIn("minimumSize:", qml)
        self.assertIn("screen.width - Style.gapsOut * 2", qml)
        self.assertIn("screen.height - Style.gapsOut * 2", qml)
        self.assertGreaterEqual(qml.count("columns: keySurface.narrow ? 1 : 2"), 1)
        self.assertIn("text: root.currentProfile.name.toUpperCase()", qml)
        self.assertIn("clip: true", qml)
        self.assertIn("keySurface.narrow ? card.width * 0.22 : card.width * 0.16", qml)
        self.assertIn("Layout.maximumWidth: keySurface.narrow ? card.width * 0.30 : Style.space(228)", qml)
        self.assertIn("Layout.minimumWidth: Style.space(200)", qml)
        self.assertIn("keySurface.narrow ? card.width * 0.72 : card.width * 0.30", qml)
        self.assertIn("keySurface.narrow ? card.width * 0.44 : card.width * 0.54", qml)
        self.assertIn("Layout.minimumWidth: Style.space(240)", qml)
        self.assertIn("readonly property bool readerLayout", qml)
        self.assertIn("readonly property bool inspectorArticleMode", qml)
        self.assertIn("property bool inspectorFactsOpen: false", qml)
        self.assertIn("function inspectorMetaLine()", qml)
        self.assertIn("RadarModel.usesQuietCard", qml)
        self.assertIn("keySurface.narrow\n                    ? index !== root.selectedIndex", qml)
        self.assertIn("RadarModel.isReaderArticle", qml)
        self.assertIn("RadarModel.humanDate", qml)
        self.assertNotIn("card.width * 0.13", qml)
        self.assertNotIn("card.width * 0.52", qml)
        self.assertNotIn("card.width * 0.27", qml)
        self.assertNotIn("card.width * 0.15", qml)
        self.assertNotIn("card.width * 0.48", qml)
        self.assertNotIn("card.width * 0.31", qml)
        self.assertNotIn("card.width * 0.46", qml)
        self.assertNotIn("card.width * 0.29", qml)
        self.assertIn("panelWindow.maximized", qml)
        self.assertIn("startSystemResize", qml)
        self.assertIn("Load more", qml)
        self.assertNotIn("BUILT-IN SECTION RULE", qml)
        self.assertIn("METRICS", qml)
        self.assertIn("readonly property bool inspectorYouTube", qml)
        self.assertIn("id: inspectorMeta", qml)
        self.assertIn("id: inspectorReadDivider", qml)
        self.assertIn("id: inspectorBody", qml)
        self.assertIn("id: inspectorActions", qml)
        self.assertIn("id: inspectorFactsToggle", qml)
        self.assertIn("id: inspectorFactsDivider", qml)
        self.assertIn("id: inspectorMetadata", qml)
        self.assertIn("visible: root.inspectorYouTube && root.inspectorHasMetrics", qml)
        self.assertIn("visible: root.inspectorFactsOpen && !root.inspectorYouTube && root.inspectorHasMetrics", qml)
        self.assertIn("foreground: root.quietTextColor", qml)
        self.assertLess(qml.find("id: inspectorMeta"), qml.find("id: inspectorReadDivider"))
        self.assertLess(qml.find("id: inspectorReadDivider"), qml.find("id: inspectorBody"))
        self.assertLess(qml.find("id: inspectorBody"), qml.find("id: inspectorActions"))
        self.assertLess(qml.find("id: inspectorActions"), qml.find("id: inspectorFactsToggle"))
        self.assertLess(qml.find("id: inspectorFactsToggle"), qml.find("id: inspectorFactsDivider"))
        self.assertLess(qml.find("id: inspectorFactsDivider"), qml.find("id: inspectorMetadata"))
        self.assertIn("MetricStrip", qml)
        self.assertIn("PanelActionButton", qml)
        self.assertNotIn('iconText: "−"', qml)
        self.assertNotIn("panelWindow.minimized", qml)
        self.assertIn('iconText: panelWindow.maximized ? "❐" : "□"', qml)
        self.assertIn('iconText: "×"', qml)
        self.assertIn('label: "Plugin page"', qml)
        self.assertIn("function pluginPageGeometry()", qml)
        self.assertIn("function readStateGeometry()", qml)
        self.assertIn("function restoreStoryViewport(revision)", qml)
        self.assertIn('property string activeProjectionViewportMode: "reset"', qml)
        self.assertIn("function queueViewportPreservation(contentY, anchorIndex, anchorTop, revision)", qml)
        self.assertIn("function applyPendingViewportPreservation()", qml)
        self.assertIn("property int pendingViewportAttempts: 0", qml)
        self.assertIn("property int forcedTopAnchorIndex: -1", qml)
        self.assertIn("pendingViewportAttempts = 24", qml)
        self.assertIn("id: viewportPreservationTimer", qml)
        self.assertIn("interval: 16", qml)
        self.assertIn("viewportPreservationTimer.start()", qml)
        self.assertIn("viewportPreservationTimer.stop()", qml)
        self.assertIn("applyPendingViewportPreservation()", qml)
        self.assertIn("id: renderedStoryModel", qml)
        self.assertIn("function syncRenderedStories(previousStories, nextStories, preserveViewport)", qml)
        self.assertIn("renderedStoryModel.append({ payload: nextStories[appendedIndex] })", qml)
        self.assertIn("JSON.stringify(previousStories[retainedIndex])", qml)
        self.assertIn("model: renderedStoryModel", qml)
        self.assertIn("cacheBuffer: height", qml)
        self.assertIn("pendingViewportAnchorTop = forcedTopAnchorIndex === anchorIndex ? 0 : anchorTop", qml)
        self.assertIn("pendingViewportAnchorIndex >= 0 && !anchorRow && pendingViewportAttempts > 0", qml)
        self.assertIn("if (anchorRow && pendingViewportAttempts > 0)", qml)
        self.assertIn("onStopped: root.applyPendingViewportPreservation()", qml)
        self.assertIn("var resumeTopAlignment = preserveViewport && storyScrollAnimation.running", qml)
        self.assertIn("if (resumeTopAlignment) storyScrollAnimation.stop()", qml)
        self.assertIn("root.animateStoryPosition(\n              resumeAnchorIndex", qml)
        self.assertIn('requestProjection("preserve")', qml)
        self.assertIn('path: root.cacheBase + "/omarchy-news-radar/feed.json"', qml)
        self.assertIn("function syncCachedEdition()", qml)
        self.assertIn("function handleCacheSync(raw)", qml)
        self.assertIn("Adopted a newer validated edition fetched in the background.", qml)
        self.assertIn("property int storyViewportRevision: 0", qml)
        self.assertIn("anchorTopAligned:", qml)
        self.assertIn("storyList.positionViewAtEnd()", qml)
        self.assertIn("function storyViewportState()", qml)
        self.assertIn("function storyNeedsTopAnchor(index)", qml)
        self.assertIn("previousAboveViewport", qml)
        self.assertIn("selection is never invisible", qml)
        self.assertIn("var nextRowBeforeSelection = storyList.itemAtIndex(nextIndex)", qml)
        self.assertIn("if (delta > 0 && !nextRowBeforeSelection)", qml)
        self.assertIn("geometry that Qt\n      // has not created", qml)
        self.assertIn("queueViewportPreservation(\n        storyList.contentY,\n        nextIndex,\n        0,", qml)
        self.assertIn("function animateStoryPosition(index, alignAtTop, initialContentY, fallbackTargetY)", qml)
        self.assertIn("currentRow.y + currentRow.height + storyList.spacing", qml)
        self.assertIn("fallbackTargetY !== undefined && fallbackTargetY >= 0", qml)
        self.assertIn("top + row.height >= storyList.height - 0.5", qml)
        self.assertIn("if (anchorAtTop) root.storyViewportAnchorIndex = nextIndex", qml)
        self.assertIn("storyList.positionViewAtIndex(anchorIndex, ListView.Beginning)", qml)
        self.assertIn("Math.min(row.y, maximumContentY)", qml)
        self.assertNotIn("currentIndex: root.selectedIndex", qml)
        self.assertIn('property: "contentY"', qml)
        self.assertIn("duration: 140", qml)
        self.assertIn("function loadMore() {\n    if (!hasMoreStories) return", qml)
        self.assertIn('requestProjection("preserve")', qml)
        self.assertIn("loadMoreButton.forceActiveFocus(Qt.TabFocusReason)", qml)
        self.assertIn("Returning\n        // focus must not reposition", qml)
        self.assertNotIn("selectStory(stories.length - 1, true)", qml)
        self.assertIn("loadMoreFocused: loadMoreButton.activeFocus", qml)
        self.assertIn("loadMoreLabel: loadMoreButton.label", qml)
        self.assertIn('"Press Enter to load "', qml)
        self.assertIn('tooltipText: "Down to focus · Enter to load the next page"', qml)
        self.assertIn('iconText: root.refreshing ? "↻" : ""', qml)
        self.assertIn("iconSpinning: root.refreshing", qml)
        self.assertIn('label: root.refreshing ? "Checking…" : "Check for updates"', qml)
        self.assertIn('tooltipText: "Check the published edition (R)"', qml)
        self.assertIn('"set-read", "--event-id"', qml)
        self.assertIn('"--retained-read-ids-json"', qml)
        self.assertIn("property var unreadSessionRetainedIds: ({})", qml)
        self.assertIn("just read shown until this view changes", qml)
        self.assertIn('"mark-section-read"', qml)
        self.assertIn('result.status === "stale-event"', qml)
        self.assertIn('label: root.bulkReadInFlight ? "Marking read…" : "Mark all as read"', qml)
        self.assertIn("function markAllReadGeometry()", qml)
        self.assertIn("id: headerUnreadButton", qml)
        self.assertIn('label: root.currentFilter.unreadOnly ? "Unread only" : "All"', qml)
        self.assertIn("function headerUnreadGeometry()", qml)
        self.assertIn('onClicked: root.updateFilter("unreadOnly", !root.currentFilter.unreadOnly)', qml)
        self.assertIn("id: keysLegend", qml)
        self.assertIn("quietTextColor", qml)
        self.assertIn('text: root.keysLegendOpen ? "Keys ▾" : "Keys · ?"', qml)
        self.assertNotIn("Keyboard shortcuts collapsed preview", qml)
        self.assertNotIn("Esc/q · j/k ·", qml)
        keys_start = qml.find("id: keysLegend")
        keys_end = qml.find("id: storyList")
        self.assertGreater(keys_start, 0)
        self.assertGreater(keys_end, keys_start)
        self.assertNotIn("BorderSurface", qml[keys_start:keys_end])
        self.assertIn("id: keysLegendToggle", qml)
        self.assertIn("property bool keysLegendOpen: false", qml)
        self.assertIn("function setSectionVisibility(sectionId, visible)", qml)
        self.assertIn('--section-visibility-json', qml)
        self.assertIn('text: root.currentSection === "youtube" ? "TIME RANGE" : "TIME WINDOW"', qml)
        self.assertIn("function keysLegendGeometry()", qml)
        self.assertIn('{ keys: "a", action: "all-read" }', qml)
        self.assertIn('{ keys: "f", action: "unread" }', qml)
        self.assertIn('{ keys: "?", action: "keys" }', qml)
        self.assertLess(qml.find('text: "SECTIONS"'), qml.find("id: keysLegend"))
        self.assertLess(qml.find("id: keysLegend"), qml.find("id: storyList"))
        self.assertIn('toLowerCase() === "a"', qml)
        self.assertIn("root.markCurrentSectionRead()", qml)
        self.assertIn("matching this section's Settings", qml)
        self.assertIn('label: root.selectedStory && root.selectedStory.isUnread ? "Mark read" : "Mark unread"', qml)
        self.assertNotIn("mark-seen", qml)
        self.assertNotIn("metricSources", qml)
        self.assertIn("SECTION SETTINGS", qml)
        self.assertIn('label: "⚙ Settings"', qml)
        self.assertNotIn('label: "⚙ Filters"', qml)
        self.assertIn("function settingsGeometry()", qml)
        self.assertIn("function refreshGeometry()", qml)
        self.assertIn("sectionSettingsOpen", qml)
        self.assertIn("SOURCES · FIXED FOR THIS SECTION", qml)
        self.assertNotIn("set-section-profile", qml)
        self.assertNotIn("sectionNameField", qml)
        self.assertNotIn("sectionIconSparkButton", qml)
        self.assertNotIn("sectionToneAccentButton", qml)
        self.assertNotIn("BACKGROUND · THEME-DERIVED", qml)
        self.assertNotIn("display name", qml)
        self.assertNotIn("Reset name", qml)
        self.assertNotIn("Local-only ·", qml)
        self.assertNotIn("Apply interests", qml)
        self.assertNotIn("interestField", qml)
        self.assertNotIn("--interests-json", qml)
        self.assertIn("if (opened && panelWindow.visible) {", qml)
        self.assertIn('startProcess(windowProc, ["activate-window"])', qml)
        self.assertNotIn("panelWindow.requestActivate()", qml)
        self.assertIn('runShortcutHelper("status")', qml)
        self.assertIn('runShortcutHelper("install")', qml)
        self.assertIn('result.classification === "owned-legacy"', qml)
        self.assertIn('label: root.shortcutState === "failed" ? "Retry shortcut update" : "Update shortcut"', qml)
        self.assertIn("function shortcutMigrationGeometry()", qml)
        self.assertIn("function dismiss() {", qml)
        self.assertIn('root.close()\n    if (shell && typeof shell.hide === "function") shell.hide(pluginId)', qml)
        self.assertIn("function emptyStateMessage()", qml)
        self.assertNotIn('id: "community"', qml)
        self.assertNotIn('currentSection === "community"', qml)
        self.assertNotIn("KEYBOARD  ", qml)
        self.assertNotIn("Color.muted", qml)
        self.assertIn('readonly property string compositorWindowTitle: "📰 Omarchy News Radar"', qml)
        button = (ROOT / "src/components/RadarButton.qml").read_text(encoding="utf-8")
        self.assertIn("preventStealing: true", button)
        self.assertIn("onClicked: root.clicked()", button)
        self.assertIn("RotationAnimation on rotation", button)
        self.assertIn('property string tooltipText: ""', button)
        self.assertIn("PanelToolTip", button)

    def test_every_section_boundary_uses_the_same_canonical_five_ids(self) -> None:
        expected = list(CLIENT_SECTIONS)
        qml = (ROOT / "src/Panel.qml").read_text(encoding="utf-8")
        qml_navigation = re.findall(r'Object\.assign\(\{ id: "([a-z-]+)" \}', qml)

        self.assertEqual(expected, qml_navigation)
        self.assertEqual(set(expected), set(SECTION_SOURCE_SUMMARIES))
        self.assertEqual(set(expected), set(SECTION_EVENT_TYPES))

        story = (ROOT / "src/components/StoryRow.qml").read_text(encoding="utf-8")
        self.assertIn("secondaryTextColor: selected", story)
        self.assertIn("Color.popups.text", story)
        self.assertIn("textFormat: Text.PlainText", story)
        self.assertIn("property bool quiet: false", story)
        self.assertIn("RadarModel.humanDate", story)
        self.assertIn("visible: !root.quiet", story)
        self.assertIn("visible: root.quiet", story)
        self.assertIn("MetricStrip", story)
        self.assertIn("● UNREAD", story)
        self.assertIn("✓ READ", story)
        self.assertIn("story.isUnread", story)
        self.assertIn("readonly property string cardSummary", story)
        self.assertIn("readonly property string cardDate", story)
        self.assertIn("story.listSummary || story.summary", story)
        self.assertIn("text: root.cardSummary", story)
        self.assertNotIn("Color.muted", story)
        model_js = (ROOT / "src/Model.js").read_text(encoding="utf-8")
        self.assertIn("function humanDate", model_js)
        self.assertIn("function isReaderArticle", model_js)
        self.assertIn("function usesQuietCard", model_js)
        self.assertIn("function articleSegments", model_js)
        self.assertIn("function articleBodyHtml", model_js)
        self.assertIn("<br/><br/>", model_js)
        self.assertIn("function acceptedHttpsUrl", model_js)
        self.assertIn('type === "omarchy-news"', model_js)
        self.assertIn('id === "core"', model_js)
        self.assertIn('id === "front-page"', model_js)
        self.assertNotIn("signal hovered", story)
        self.assertNotIn("onHovered:", qml)
        self.assertIn("item[\"listSummary\"] = list_summary", (ROOT / "radar/client.py").read_text(encoding="utf-8"))
        self.assertIn("text: root.inspectorBodyText()", qml)
        self.assertIn('item["summarySegments"] = article_segments', (ROOT / "radar/client.py").read_text(encoding="utf-8"))

        section = (ROOT / "src/components/SectionButton.qml").read_text(encoding="utf-8")
        self.assertIn("property string icon", section)
        self.assertIn("property string tone", section)
        self.assertIn("Color.accent", section)
        self.assertIn("Color.foreground", section)
        self.assertIn("Style.font.iconLarge", section)
        self.assertIn("id: iconText", section)
        self.assertIn("property int unreadCount", section)
        self.assertNotIn("Color.muted", section)

        metrics = (ROOT / "src/components/MetricStrip.qml").read_text(encoding="utf-8")
        for metric_id in (
            "marketplace-views",
            "marketplace-hearts",
            "marketplace-copies",
            "repository-stars",
            "release-asset-downloads",
        ):
            self.assertIn(metric_id, metrics)
        self.assertIn("Color.accent", metrics)
        self.assertIn("Accessible.name", metrics)

    def test_complete_keyboard_and_visible_state_labels_exist(self) -> None:
        qml = (ROOT / "src/Panel.qml").read_text(encoding="utf-8")
        for key in (
            "Qt.Key_Escape",
            "Qt.Key_Down",
            "Qt.Key_Up",
            "Qt.Key_Return",
            "Qt.Key_Home",
            "Qt.Key_End",
            "Qt.Key_Tab",
            "Qt.Key_Backtab",
            "Keys.onEscapePressed",
            'event.text === "/"',
            'toLowerCase() === "s"',
            'toLowerCase() === "u"',
            'toLowerCase() === "f"',
            'toLowerCase() === "a"',
            '=== "?"',
            'toLowerCase() === "r"',
        ):
            self.assertIn(key, qml)
        for state in ("First use", "Cached", "Checking", "Updated", "No newer edition", "Publisher stale", "Offline", "Source partial", "Invalid feed", "No cache and failed"):
            self.assertIn(state, qml)


if __name__ == "__main__":
    unittest.main()
